### ISSUE TITLE
Error in memory specification

### ISSUE THREAD

**Issue by takekazuomi** [smurawski/docker-compose-examples#1]
The resource size was specified as follows.

```yaml
services:
  helloworld:
    image: mcr.microsoft.com/azuredocs/containerapps-helloworld:latest
    ports: 
     - 8080:80
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 0.5GB
```
The result is as follows.

```sh
$ az containerapp compose create --environment simple-0792  --resource-group simple-0297
Command group 'containerapp compose' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
'ComposeByteValue' object has no attribute 'gigabytes'
Traceback (most recent call last):
  File "/opt/az/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/takekazu/.azure/cliextensions/containerapp-compose/azext_containerapp_compose/custom.py", line 154, in create_containerapps_from_compose
    resolve_memory_configuration_from_service(service)
  File "/home/takekazu/.azure/cliextensions/containerapp-compose/azext_containerapp_compose/custom.py", line 332, in resolve_memory_configuration_from_service
    memory = str(resources.reservations.memory.gigabytes())
AttributeError: 'ComposeByteValue' object has no attribute 'gigabytes'
To open an issue, please run: 'az feedback'
```
ComposeByteValue is `.as_gigabytes()` instead of `.gigabytes()`. I think.

The docker compose support is great. Thank you. 🎉

**Comment by usepowershell** [comment]
This should be fixed in v0.2.0 which should now be available.  Thanks @takekazuomi
